on:
  push: {}
name: Publish
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo test --all-features
    #  - run: cargo publish --token ${CRATES_TOKEN}
    #    env:
    #      CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}